### ISSUE TITLE
Support for timezone in SignalFlow execution

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [signalfx/signalfx-python#113]
https://dev.splunk.com/observability/reference/api/signalflow/latest#endpoint-start-signalflow-computation

SignalFlow execute endpoint supports setting a timezone, which is very relevant when aggregating by days, weeks, etc.

It would be great if the library also supported that.

**Comment by hubertgrzeskowiak** [comment]
Workaround I am using:
```
flow = sfx.signalflow(TOKEN)

def _get_params(**kwargs):
    kwargs["timezone"] = "Australia/Sydney"
    return dict((k, v) for k, v in kwargs.items() if v is not None)

flow._get_params = _get_params
flow.execute(...)
```

**Comment by hubertgrzeskowiak** [comment]
For this fix I reckon it would be enough to add another param `timezone` to [execute](https://github.com/signalfx/signalfx-python/blob/master/signalfx/signalflow/__init__.py#L34).

**Comment by mpetazzoni** [comment]
@hubertgrzeskowiak indeed; would you be able to send a PR for this? Thanks!
