### ISSUE TITLE
Contradiction of documentation

### ISSUE THREAD

**Issue by makzzz1986** [signalfx/signalfx-python#115]
You have some strange behavior of SignalFX API, if I use the example from the README:
```
import signalfx

with signalfx.SignalFx().ingest('ORG_TOKEN') as sfx:
    sfx.send(
        gauges=[
          {'metric': 'myfunc.time',
           'value': 532,
           'timestamp': 1442960607000},
          ...
        ],
        counters=[
          {'metric': 'myfunc.calls',
           'value': 42,
           'timestamp': 1442960607000},
          ...
        ],
        cumulative_counters=[
          {'metric': 'myfunc.calls_cumulative',
           'value': 10,
           'timestamp': 1442960607000},
          ...
        ])
```

It doesn't work with CURL or Urllib implementations, rather than the official example [here](https://dev.splunk.com/observability/docs/#Example-Send-data-to-Infrastructure-Monitoring).
The difference in `gauge` and `gauges`. If I send metrics as `gauges`, I get `OK` response but don't see any metrics.
You can reproduce it by
```
curl --data '{"gauges": [{"metric": "argocd_backup_resources", "value": 4, "dimensions": {"environment": "staging", "kind": "ConfigMap"}}]}' -H "Content-Type: application/json" -H "X-SF-TOKEN: TOKEN" "https://ingest.eu0.signalfx.com/v2/datapoint"
```
and 
```
curl --data '{"gauge": [{"metric": "argocd_backup_resources", "value": 4, "dimensions": {"environment": "staging", "kind": "ConfigMap"}}]}' -H "Content-Type: application/json" -H "X-SF-TOKEN: TOKEN" "https://ingest.eu0.signalfx.com/v2/datapoint"
```

**Comment by mpetazzoni** [comment]
The parameters of the `send()` function are not meant to match the field names in the JSON body of the request to `/v2/datapoint`.

You can see at https://github.com/signalfx/signalfx-python/blob/master/signalfx/ingest.py#L138-L142 how the request body is built by the library. If you're making a manual request using `curl`, the field name in the request body's dictionary is `gauge`, not `gauges`.
