### ISSUE TITLE
signalfx and sseclient-py missing sdist

### ISSUE THREAD

**Issue by makmanalp** [signalfx/signalfx-python#122]
Hi, I've noticed that both of these packages are missing source distributions in pypi, and although sseclient-py isn't under this org, it seems to be developed by @mpetazzoni and I'm guessing that it's the same issue in both. Most packages generally do this and the lack of source distribution is causing some of our infra to have trouble with this package. Would it be possible to add that in?

It's mostly be something like: right before you do `twine upload dist/*`, add a `python setup.py sdist`.

Thank you!

**Comment by mpetazzoni** [comment]
This is done for `signalfx-python` starting with v1.1.14: https://pypi.org/project/signalfx/#files. I'll take care of `sseclient-py` shortly as I indeed own that project.
