### ISSUE TITLE
Release the next version of this to PyPi?

### ISSUE THREAD

**Issue by PaulFurtado** [signalfx/signalfx-python#18]
I see that version 0.3.7 was released on November 12th, 2015 going by git tags, so it's been quite a while since you've release a new version of this.

I'm looking to use the `update_dimension` method which is present on the SignalFxClient class on the master branch, but did not exist at the time of the 0.3.7 tag.

If you're not planning on doing a release soon, I can just call the private `_put` method on the SignalFxClient directly for now, so it's not a showstopper, but it would be nice if you'd release the next version soon.

Thanks,
Paul

**Comment by mdubbyap** [comment]
Yes, we just merged that code and will be releasing it imminently.  Will update you when it's done.  

matthew.

**Comment by mdubbyap** [comment]
signalfx 0.3.8 has been released!
