### ISSUE TITLE
Python 3: AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by jtprobst** [signalfx/signalfx-python#33]
I am testing the current master branch (upcoming release 1.0.6) which I installed with

```pip install git+https://github.com/signalfx/signalfx-python```

and when sending a data point with the ingest API, I get the error:

```
[previous stack frames come from my application...]
  File "/usr/local/lib/python3.4/dist-packages/signalfx/ingest.py", line 121, in send
    for metric_type, datapoints in data.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

Python version is 3.4 inside Ubuntu 14.04, installed using the package manager.

**Comment by mpetazzoni** [comment]
Fixed in v1.0.7.
