### ISSUE TITLE
explain best practices for use in gevent (or other such) environments

### ISSUE THREAD

**Issue by saluker** [signalfx/signalfx-python#35]
Without reading the code it's hard to tell if this is gevent-safe and if signalfx.SignalFx().ingest() should be instantiated once and then sfx.send() safely used from greenlets.  Thanks.

**Comment by mpetazzoni** [comment]
`sfx.send()` puts the given datapoints onto a queue which is continuously drained by a background sending thread. The creation and start of that thread are thread-safe, and so are the calls to `sfx.send()`, which enqueue onto a Python `queue` (a synchronized datastructure).

**Comment by saluker** [comment]
Thanks, that helps.
