### ISSUE TITLE
Signalfx client not working from Multiprocessing

### ISSUE THREAD

**Issue by CaptBeardie** [signalfx/signalfx-python#48]
Looks like when running signalfx client within a forked process using the 'multiprocessing' module, it fails to send any data.

https://gist.github.com/anonymous/9194c5b8619296fe39544f3405ce939c

**Comment by mpetazzoni** [comment]
This is a problem between `multiprocessing` and `atexit`, not with the SignalFx client itself.

Just call `sfx.stop()` directly after your `sfx.send(...)`.

**Comment by CaptBeardie** [comment]
Thanks!
