### ISSUE TITLE
How to pull data points with signalflow in a (semi) non-blocking manner?

### ISSUE THREAD

**Issue by smallredbean** [signalfx/signalfx-python#56]
[The example code of executing a signalflow computation](https://github.com/signalfx/signalfx-python#executing-signalflow-computations) illustrates a way to retrieve data points where the data pulling is blocked at "computation.stream()" if non is reaady, quote

```python
program = "data('cpu.utilization').mean().publish()"
with signalfx.SignalFx().signalflow('MY_TOKEN') as flow:
    computation = flow.execute(program)
    for msg in computation.stream():  # <-- blocked here
        ...
```

Is there a way to "peek" at the stream to learn if there's data there, e.g., "computation.has_msg()"? Or make "computation.stream()" return if no msg is ready, instead of busy waiting in the inside while-loop?

**Comment by mpetazzoni** [comment]
It's not possible out of the box because it's better for the library to expose one simple and flexible way to access the computation's output: via the _generator_ returned by `stream()`. From there, you're free to consume it however you want. In your case, you can easily pull it into a queue:

```python
import queue
import threading

sentinel = object()
def drain(program, q):
    with signalfx.SignalFx().signalflow('TOKEN') as flow:
        for msg in flow.execute(program).stream():
            q.put(msg)
        q.put(sentinel)

q = queue.Queue(maxsize=1024)
threading.Thread(target=drain, args=(program, q)).start()

# Do what you want with q here, like q.get_nowait()
```
