### ISSUE TITLE
python3.6 support

### ISSUE THREAD

**Issue by smallredbean** [signalfx/signalfx-python#57]
Hi, could you help add python3.6 support? Thanks!

**Comment by mpetazzoni** [comment]
The library should work fine with Python 3.x, as you can see by our build and tests at https://travis-ci.org/signalfx/signalfx-python. I haven't directly tested with 3.6 though; was there anything in particular that you ran into that caused a problem?

**Comment by smallredbean** [comment]
Not really. This is more for double checking. We are building a new service with your package and wondering if python3.6 can be an option; you only include py35 in the testing target.

We can definitely take a shot on python3.6 and report back if any issue.

**Comment by mpetazzoni** [comment]
Great! Looks like it builds and passes current tests fine: https://travis-ci.org/signalfx/signalfx-python/jobs/236118154

Test coverage isn't awesome, but I don't expect major problems. Give it a shot, feel free to open issues and/or PRs if you run into anything!
