### ISSUE TITLE
HTTP request hits ReadTimeout when posting data

### ISSUE THREAD

**Issue by ram-nadella** [signalfx/signalfx-python#69]
We capture exceptions using Sentry and we regularly see read timeout exceptions from the signalfx library.

```
HTTPSConnectionPool(host='ingest.signalfx.com', port=443): Read timed out. (read timeout=1)
```

Looks like this happens when the ingest endpoint is unable to respond within a second.

Does this mean the data point was dropped? Is there a way to increase this value or even allow this value to be customized?

A longer timeout means connections stay open longer waiting for a response, could this cause issues with potentially piling up connections or thread on the client side? Haven't dug into the code yet, wondering what the potential downside to bumping this up to say 3 seconds is.

Here is the exception and stack trace (most recent call first):

```
ReadTimeout: HTTPSConnectionPool(host='ingest.signalfx.com', port=443): Read timed out. (read timeout=1)
  File "signalfx/ingest.py", line 207, in _send
    self._INGEST_ENDPOINT_DATAPOINT_SUFFIX))
  File "signalfx/ingest.py", line 223, in _post
    response = session.post(url, data=data, timeout=timeout)
  File "requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "raven/breadcrumbs.py", line 326, in send
    resp = real_send(self, request, *args, **kwargs)
  File "requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
```

Thread name: 'SignalFxDatapointSendThread'

Most recent error we saw was on *Jun 3, 2018* at *2:20:20 AM EDT* and I said this is a periodic occurrence we keep running into. Does not appear to have a pattern from what we can tell.

**Comment by mpetazzoni** [comment]
If you're using a recent version of `signalfx-python`, the default timeout is now 5 seconds, which will definitely help here. If you can't upgrade, you can still change the timeout used when sending datapoints to SignalFx's ingest API by passing the `timeout` parameter either to the `SignalFx()` constructor, or when calling `.ingest()` to get the ingest client:

```python
import signalfx
sfx = signalfx.SignalFx().ingest(timeout=5)
```

Feel free to re-open if this doesn't solve your issue!

**Comment by ram-nadella** [comment]
Thanks for the quick reply @mpetazzoni and we are not using the latest version of the library (we're on `1.0.9`) and I agree, the bump to 5 seconds instead of 1 should indeed help.

Will post back if upgrading doesn't resolve the timeouts.
