### ISSUE TITLE
'-' instead of value in the data table

### ISSUE THREAD

**Issue by AlphaOlish** [signalfx/signalfx-python#72]
Hello, 
I am using SignalFx to monitor an AUC metric per group_id, 
I use the following code: 
with signalfx.SignalFx().ingest(config['API_token']) as sfx:
           sfx.send(
                     gauges=[
                            {
                                'metric': 'AUC',
                                'value': avgAuc,
                                'timestamp': time.time(),
                                'dimensions': {'group_id': group_id}
                            }
                        ])
where avgAuc is float. 
But I've got '-' instead of values in the data table. I have data in avgAuc before sending. Could you, please, suggest, where can be an error?

**Comment by mpetazzoni** [comment]
@AlphaOlish timestamps sent to SignalFx must be in milliseconds since Epoch. Use:

```python
`timestamp`: int(time.time() * 1000),
```

**Comment by AlphaOlish** [comment]
Thank you!
