### ISSUE TITLE
signalFx.SignalFlowClient.execute() never returns 

### ISSUE THREAD

**Issue by tlindhardt** [signalfx/signalfx-python#89]
I have a process that current just pulls a program every minute and gets the last 5m of data.. After about a week of it constantly running I run into issues where the socket never returns any data.. I thought about using the timeout parameter but that doesnt do anything with the WebSocketTransport..

Here is my code to read the data
```
def get_program_data(self, program: str, start: datetime, stop: datetime) -> (dict, dict):
        data = {}
        metadata = {}
        with SignalFlowClient(self.__app_key, compress=True) as client:
            result = client.execute(program=program, start=self.to_epoch_ms(start),
                                    stop=self.to_epoch_ms(stop),
                                    resolution=self.__resolution, immediate=True,
                                    max_delay=10)
            for msg in result.stream():
                if isinstance(msg, messages.DataMessage):
                    if msg.logical_timestamp_ms in data:
                        data[msg.logical_timestamp_ms].update(msg.data)
                    else:
                        data[msg.logical_timestamp_ms] = msg.data
                elif isinstance(msg, messages.MetadataMessage):
                    metadata[msg.tsid] = msg.properties

        return data, metadata
```

The strange thing is it runs fine for a couple days and then just hangs.. 

The range is pretty short as well... 
`now - timedelta(minutes=5), now`

Any tips/advice would be super helpful.. Im not sure what exactly could be going on as no errors have bubbled up..

**Comment by tlindhardt** [comment]
Ive looked into using the SSE client but it only has a Connect timeout.. Perhaps I could open a PR to allow a read timeout as well?

**Comment by mpetazzoni** [comment]
@tlindhardt Please reach out to support with more information about the metric timeseries you're trying to get data from. We'd be able to look at their reporting behavior and lag and run some tests ourselves to better assist you.
