### ISSUE TITLE
SSL Error when connecting with the python client.

### ISSUE THREAD

**Issue by Bernie** [signalfx/signalfx-python#9]
When attempting to connect to signalfx with the provided python client, the following SSL error occurs:\\

SSLError: hostname 'api.signalfx.com' doesn't match either of '*.signalfuse.com', 'signalfuse.com'

Here's the full log:

INFO:urllib3.connectionpool:Starting new HTTPS connection (4): api.signalfx.com
ERROR:root:Posting to SignalFx failed.
Traceback (most recent call last):
  File ".../signalfx/__init__.py", line 188, in _post
    response = _session.post(url, data=data, timeout=self._timeout)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
SSLError: hostname 'api.signalfx.com' doesn't match either of '*.signalfuse.com', 'signalfuse.com'

**Comment by ramjothikumar** [comment]
We use SSL SNI in our prod API and you are probably running a version of
python-requests modules that does not supports this. Can you check if your
python requests version is >= 2.7.0 (pip freeze | grep requests) and if not
upgrade it.
Also, you need to upgrade your python version to 2.7.8/9/10 if you are
sending events.

- ram

**Comment by mpetazzoni** [comment]
I can confirm that upgrading to Python 2.7.9 or above, with `requests >= 2.7.0` fixes this problem. I'll close this issue.
